### ISSUE TITLE
Testing start date and end date assignment

### ISSUE THREAD

**Issue by camelPhonso** [enBloc-org/.github#13]
### Expected Behavior

not a real issue

### Current Behavior

automation should assign start and end dates

### Assignment

This issue is free for anyone to take

**Comment by nourakhy** [comment]
maybe this will help
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler
